In [1]:
%load_ext Cython
import numpy as np
from numpy.random import randint

import pyximport; pyximport.install(reload_support=True, setup_args={'include_dirs':np.get_include()})

import timeit

%load_ext autoreload
%autoreload 2

In [2]:
# import rlencode as runl
import rlencode as runl

In [3]:
np.random.seed(2)
a1 = np.random.randint(0, 2, 10)
ao = runl.encode(a1, 1, 1)
a2 = randint(0, 2, (4,3))
ao2 = runl.encode(a2)
a3 = randint(0, 2, (4,3,2))
ao3 = runl.batch_encode(a3)

print(a1)
print(ao)
print(a2)
print(ao2)
print(a3)
print(ao3)

[0 1 1 0 0 1 0 1 0 1]
[ 2  2  6  1  8  1 10  1]
[[0 1 1]
 [1 1 1]
 [1 1 0]
 [0 0 0]]
[2 2 5 3 9 2]
[[[1 1]
  [1 0]
  [0 0]]

 [[1 1]
  [1 0]
  [0 1]]

 [[0 0]
  [1 1]
  [1 0]]

 [[0 0]
  [0 1]
  [1 1]]]
[array([1, 2, 4, 1]), array([1, 2, 4, 1, 6, 1]), array([2, 2, 5, 1]), array([3, 1, 5, 2])]


In [4]:
timeit_setup = """
import rlencode as runl
import numpy as np
from numpy.random import randint
np.random.seed(2)
a2 = randint(0, 2, (75,75))
"""

print(timeit.timeit('ao2 = runl.encode(a2)', setup=timeit_setup, number=100000))
# 100,000 iterations of 75x75 matrices = ~5.5 second on mid-2012 MACBook Pro 8GB Memory

timeit_setup2 = """
import rlencode as runl
import numpy as np
from numpy.random import randint
np.random.seed(2)
ba1 = randint(0, 2, (10000, 75, 75))
"""
print(timeit.timeit('bao1 = runl.encode(ba1)', setup=timeit_setup2, number=3))
# 10,000 75x75 matrices = ~5.2 second on mid-2012 MACBook Pro 8GB Memory

In [5]:
a4 = randint(0, 2, (4,3,2))
ao4 = runl.batch_encode(a4, to_string=True)

print(ao4)

['1 1', '3 1 5 2', '1 1 4 1 6 1', '2 1 4 3']
